### PR TITLE
ASDK -> Texture and update the version to 2.3.2

### PR DESCRIPTION
**Pull request by suprie**
Addressing issue #131

Change AsyncDisplayKit to Texture, 
Update the version of Texture to latest version (2.3.2),
Fix error caused by upgrading

### CODE REVIEW

**Comment by alexandremorgado** [comment]
I tested this PR and it work's fine on my app. Unfortunately the  of the NMessenger seem to be without time to prioritize the PR reviews...

**Comment by dodikk** [comment]
> Unfortunately the of the NMessenger seem to be without time to prioritize the PR reviews...

Yeah. Really sad.

 My earliest PRs have **no feedback** for more than `2 months`.
Already `6 pending`...

screen shot 2017-07-20 at 7 10 24 pm

**Comment by dodikk** [comment]
Can anyone suggest a good maintainable fork ?

**Comment by schechd** [comment]
@dodikk I understand your frustration with the repo not being updated and PR not being accepted. I am currently with a Macbook, and therefore cannot work on this project,

I it important to me to maintain and update this project on a regular basis.

I am planning on buying new Macbook in the next couple of months, and working on all the PRs and issues when I get it.

@atainter do you time in the meanwhile to review PRs and issues?

Thanks,
David Schechter

**Comment by DavidSchechter** [comment]
@dodikk I understand your frustration with the repo not being updated and PR not being accepted. I am currently with a Macbook, and therefore cannot work on this project.

It important to me to maintain and update this project on a regular basis.

I am planning on buying new Macbook in the next couple of months, and working on all the PRs and issues when I get it.

@atainter do you time in the meanwhile to review PRs and issues?

Thanks,
David Schechter

**Comment by suprie** [comment]
@DavidSchechter Take your time dude,  I understand you might don't have enough time for reviewing all PR's. 
I'd suggest to recruit other person to help you and your team to review the PR's or help you develop this awesome project.  So it might help you a little bit

**Comment by atainter** [comment]
@suprie @DavidSchechter @dodikk 
Hi all,

As much as I would like to contribute to open source, I don't think I can right now because of my other responsibilities. I might have time to jump back in at some point, but I don't know when that will be. 

In the meantime, I'll talk to our legal team about adding maintainers to the project.

Aaron

**Comment by atainter** [comment]
@alexandremorgado @dodikk You both seem pretty active on this project. Would you be interested in becoming contributors?

**Comment by dodikk** [comment]
Let's continue the discussion in a separate thread https://github.com/eBay/NMessenger/issues/149

**Pull request merged**
